export const devices = {
  mobile: [
    {
      name: "iPhone SE",
      width: 375,
      height: 667,
      scale: 0.9,
      category: "Mobile",
    },
    {
      name: "iPhone 14 Pro",
      width: 390,
      height: 844,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "iPhone 14 Pro Max",
      width: 428,
      height: 926,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "Google Pixel 5",
      width: 393,
      height: 851,
      scale: 1,
      category: "Mobile",
    },
    {
      name: "Google Pixel 7 Pro",
      width: 412,
      height: 915,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "Samsung Galaxy S20",
      width: 360,
      height: 800,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "Samsung Galaxy S22 Ultra",
      width: 384,
      height: 854,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "OnePlus 9",
      width: 412,
      height: 915,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "Sony Xperia 1",
      width: 360,
      height: 780,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "Huawei P40 Pro",
      width: 392,
      height: 800,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "Xiaomi Mi 11",
      width: 392,
      height: 832,
      scale: 0.8,
      category: "Mobile",
    },
    {
      name: "Oppo Find X3 Pro",
      width: 393,
      height: 876,
      scale: 0.8,
      category: "Mobile",
    },
  ],
  tablets: [
    {
      name: "iPad Mini",
      width: 768,
      height: 1024,
      scale: 0.7,
      category: "Tablet",
    },
    {
      name: "iPad Air",
      width: 820,
      height: 1180,
      scale: 0.7,
      category: "Tablet",
    },
    {
      name: "iPad Pro 11",
      width: 834,
      height: 1194,
      scale: 0.7,
      category: "Tablet",
    },
    {
      name: "iPad Pro 12.9",
      width: 1024,
      height: 1366,
      scale: 0.6,
      category: "Tablet",
    },
    {
      name: "Samsung Galaxy Tab S7",
      width: 800,
      height: 1280,
      scale: 0.7,
      category: "Tablet",
    },
    {
      name: "Samsung Galaxy Tab S8 Ultra",
      width: 800,
      height: 1280,
      scale: 0.7,
      category: "Tablet",
    },
    {
      name: "Microsoft Surface Pro 7",
      width: 912,
      height: 1368,
      scale: 0.7,
      category: "Tablet",
    },
    {
      name: "Amazon Fire HD 10",
      width: 800,
      height: 1280,
      scale: 0.7,
      category: "Tablet",
    },
    {
      name: "Lenovo Tab P11",
      width: 800,
      height: 1200,
      scale: 0.7,
      category: "Tablet",
    },
    {
      name: "Huawei MatePad Pro",
      width: 800,
      height: 1280,
      scale: 0.7,
      category: "Tablet",
    },
  ],
  computers: [
    {
      name: "MacBook Air",
      width: 1440,
      height: 900,
      scale: 1,
      category: "Computer",
    },
    {
      name: "MacBook Pro 14",
      width: 1512,
      height: 982,
      scale: 1,
      category: "Computer",
    },
    {
      name: "MacBook Pro 16",
      width: 1728,
      height: 1117,
      scale: 1,
      category: "Computer",
    },
    {
      name: "iMac 24",
      width: 1920,
      height: 1080,
      scale: 0.8,
      category: "Computer",
    },
    {
      name: "Dell XPS 13",
      width: 1920,
      height: 1080,
      scale: 0.8,
      category: "Computer",
    },
    {
      name: "Microsoft Surface Laptop 4",
      width: 2256,
      height: 1504,
      scale: 0.8,
      category: "Computer",
    },
    {
      name: "ASUS ROG Zephyrus G14",
      width: 2560,
      height: 1440,
      scale: 0.8,
      category: "Computer",
    },
    {
      name: "Lenovo ThinkPad X1",
      width: 1920,
      height: 1200,
      scale: 0.8,
      category: "Computer",
    },
    {
      name: "HP Spectre x360",
      width: 1920,
      height: 1080,
      scale: 1,
      category: "Computer",
    },
    {
      name: "Acer Swift 3",
      width: 1920,
      height: 1080,
      scale: 1,
      category: "Computer",
    },
  ],
};
